INSERT INTO `user` (`id`, `account`, `password`) VALUES (1, 'Root', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (2, 'Maple', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (3, 'Lorem', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (4, 'Augmentation', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (5, 'Loss', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (6, 'BigGAN', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (7, 'Chinese', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (8, 'Edit', '123');
INSERT INTO `user` (`id`, `account`, `password`) VALUES (12, 'Shao', '123');
